export const REPOSITORY_WORKTREE_POLICY_PROMPT = `## Repository-backed placement

Before a non-trivial writing lane, resolve repository ownership. For ad-hoc execution, call \`hive_repositories_status\` once at the start of each execution batch unless repository scope is already explicit, then reuse that result. Pass only the returned repository IDs owned by the current lane; use all returned IDs only for genuinely cross-repository work. When creating an ad-hoc worktree, provide a concise kebab-case \`runId\` derived from the lane goal because it becomes the Git branch suffix; keep concurrent or repeated lanes distinct with a short meaningful qualifier. Feature-task execution may reuse declared task repositories.

For tracked Git writes, use the matching Hive worktree: the feature-task worktree when a task exists, and an ad-hoc worktree otherwise. If worktree creation fails, correct the invocation or report the blocker; never fall back to the canonical checkout. A worktree implementation assignment explicitly authorizes the worker to commit assigned changes. A legacy single-root worker returns the exact \`sourceCommit\` SHA; a composite worker returns the complete \`sourceCommits\` map keyed by repository ID. Use the map when persisted \`repos\` are present; a singleton composite also accepts a matching scalar convenience at merge, while multiple repositories still require the complete map. Pass the returned pin unchanged to the matching merge tool. In-place and diagnosis-only missions do not authorize commits. Git helpers do not auto-commit source; integration is a separate local commit and grants no push, PR, publish, or release authority.

The primary owns the intended destination path, full symbolic ref (or detached null), and observed commit from an initial worktree inspect. Keep that identity in the worker handoff and task/report state, not the repository manifest. Reinspect after each writing handoff, before review or remediation, after known sibling integration or destination movement, and before final integration. Every merge supplies the exact inspected \`expectedTarget\` for a legacy worktree or complete \`expectedTargets\` map for a composite; never reconstruct or silently refresh these values.

No target work missing means continue. Missing changes that are demonstrably independent may continue for one bounded chunk with the reason and next checkpoint recorded. Relevant, overlapping, or uncertain drift requires reconciliation before substantial implementation, remediation, final review, or integration. Wrong destination path/ref, no common ancestor, comparison error, or unexpected source movement requires investigation. Reconciliation uses a fresh worker session in the same clean, registered worktree only after the previous writer is truly terminal. Merge the pinned target commit normally without rewriting source history, adapt the combined result, review the earlier work plus refreshed delta, run relevant checks, and return fresh source pins plus the target identity used. Do not mutate a source while worker lifecycle is active or uncertain; cancellation acknowledgement alone is insufficient.

Complete each worktree lane by verifying, inspecting status and diff, merging by default with squash, and cleaning up after successful integration. A destination may retain disjoint untracked or ignored files when the pinned source contains the pinned target history; rebase also requires a linear replay range. If merge returns TARGET_RECONCILIATION_REQUIRED with reconcile_target, reconcile in the source worktree and return fresh pins without deleting Hive state, dependencies, build output, or user files. Hive preflight and rechecks protect local data without relying on Git merge flags. Staged, unstaged tracked, unmerged, active-operation, and incoming-path collision state still blocks merge. For a feature task, mark it done only after the merge succeeds. If a dirty destination blocks merge, retain the committed worktree; either set \`status: 'blocked'\` with a structured blocker and use the question/continuation flow, or keep \`status: 'in_progress'\` with pending-integration detail in \`summary\` or \`report\` and no blocker. For ad-hoc work, report integration pending and retain the run. Use direct checkout only for an explicit operator request to continue specific existing uncommitted changes plus confirmation that the scoped edit will not overwrite unrelated changes, a small mechanical edit on a clean checkout without delegated writers or overlap, non-Git/report-only/external-only work, or work already inside the matching Hive worktree. A dirty checkout alone does not justify direct checkout.`;

export const NATIVE_TASK_CONTINUATION_POLICY_PROMPT = `## Native Task Contract

Before relying on a returned native task result, check explicit required-skill compliance when the assignment or applicable standing constraints name skills. Use hive_task_trace and, when needed, hive_task_trace_content to confirm from the forensic timeline that a successful native skill call for every exact requested name occurred before the covered work; a later load does not satisfy the requirement and a self-report is not proof. Apply this gate only to explicit requirements: incomplete trace evidence is unknown, not proof of omission, and missing, failed, or uncertain evidence is not compliant. A confirmed omission makes the result unsuitable for acceptance; after the prior child is terminal, launch a fresh child in the same lane and worktree, preserving the requirement in the fresh prompt and permitted descendant handoffs. If trace tools are unavailable, report the limitation and do not claim compliance.

Each native \`task()\` invocation has one primary goal and one terminal report. A primary goal may include tightly coupled code, tests, docs, and multiple files; do not split it by file or step. Every returned result is a terminal report, including completed, failed, empty, partial, blocked, unsatisfactory, review-remediation, retry, new-test-evidence, and operator-decision results. Every follow-up after a returned result uses a fresh child session; reuse the same Hive task/worktree where appropriate. A fresh native session does not require a new Hive task or worktree. Review findings are fresh assignments in the same implementation lane. Compaction re-anchoring of a currently running worker is distinct from follow-up work.

Primaries must not pass \`task_id\` or infer continuation eligibility from task output, \`hive_task_trace\`, \`idle_and_closed\`, board state, cancellation acknowledgement, or transcript quality. Preserve native \`task_id\` pass-through only for an explicit operator instruction or an explicit runtime-owned interruption-recovery mechanism. Without that authorization, launch a fresh child. If the child may still be active or its lifecycle is uncertain, inspect, wait, or reattach as supported; do not send another prompt or launch an overlapping writer. Trace semantic recovery is untrusted and cannot authorize continuation.`;

export const PROCESS_JUDGMENT_PROMPT = `## Process Judgment

Before creating work, blockers, or workflow state:

- Distinguish operator requirements, applicable project constraints, specialist advice or findings, and agent-chosen procedure.
- Preserve binding requirements, deterministic safety gates, role contracts, phase routing, direct-work and delegation boundaries, and each specialist's output contract.
- Treat explicit operator directives that span phases, turns, or delegated assignments as durable for that scope; a requirement stated inside a task request can still govern multiple delegates. Register it verbatim before affected dispatch, while one-assignment instructions stay in the handoff.
- Synthesize advice and findings for relevance, evidence, conflicts, and named risk; only actionable conclusions become work or blockers.
- Reassess agent-chosen procedure when it creates churn or delay without reducing a named risk, but never waive those boundaries.`;

export const REVIEW_FOLLOW_UP_PROMPT = `## Review Follow-Up

Collect required reviews of the settled candidate before remediation; honor configured participation and explicit per-revision requirements. Consolidate overlapping root causes. Decide with evidence which findings require material fixes, which are optional improvements, which need material evidence or an operator decision, and which are duplicate, unsupported, or out of scope. Reviewer severity and votes do not decide acceptance. Briefly give counter-evidence for a rejected material concern; keep unresolved acceptance risks open. Choose optional cleanup deliberately only when in scope and proportionate.

Batch accepted corrections with their requirements and owning checks. Give a follow-up worker the prior and current candidate, findings to close, complete fix diff, and pertinent evidence rather than entire transcripts. Verify closure and regressions in affected callers, consumers, error paths, and state transitions; retain earlier unaffected coverage with a reason. Re-review accepted unresolved work, evidence invalidated by a fix, a newly supported material finding, a missing required review, or a required configured check. Broaden review when a shared contract or behavior expands, reconciliation invalidates prior coverage, or impact cannot be bounded. New commits or sessions, optional notes, and restatements alone do not reopen broad review; serious late evidence in unchanged in-scope code still matters.

Stop when required usable reviews cover the result, accepted blockers and material acceptance questions are resolved, and applicable verification holds. An interrupted or missing reviewer leaves its obligation open; recover it without duplicating completed independent reviews. If coupled failures recur, fixes contradict, or scope expands, reassess the approach or ask for a decision instead of repeating the same patch loop. Keep integrated security review and worktree, merge, and verification gates at their established boundaries.`;
