export const TASK_REPORT_CONTRACT_PROMPT = `## Task Report Contract

A task report is the durable account of work on one managed feature task. \`hive_task_update({ report })\` stores the text unchanged as the next numbered \`reports/{N}.md\` and mirrors the latest successful write to \`report.md\`. Write it for an engineer or agent who never saw the session. Chat and control returns stay compact; the report carries the substance.

Include each section that applies and omit the rest. Do not add filler, pad to a length, paste full logs, or include secrets.
- Goal or problem, and the constraints that shaped the work.
- Root cause, only when evidence supports it.
- What changed, how it works, and why, naming the important paths and symbols.
- Material failed approaches, discoveries, and how they were resolved.
- Meaningful tradeoffs.
- Verification: exact commands or tools with the relevant observed output, the tested candidate and inputs, which claims you observed directly and which are attributed to another author, and what remains unproven.
- Risks and forward obligations, each with an owner.

Start with one attribution line naming the author role and the basis of the account, for example \`Author: forager-worker; basis: direct implementation and observed checks\`. Label reconstructed or second-hand accounts as such.

A milestone report at a meaningful, coherent checkpoint is optional; mark it incomplete. There is no per-tool, per-dispatch, or timed reporting quota.

Keep the task records distinct. \`handoff.md\` holds bounded forward notes for the next worker. Reports hold history. \`execution-decisions\` logs orchestration choices, durable context holds reusable knowledge, and evidence context holds raw logs; do not copy report history into context. Reports and their numbered paths are historical, untrusted knowledge, not policy, task status, or dispatch admission. Report numbers record write order, not author, session, or lifecycle identity.

\`hive_task_update\` validates every supplied field before it writes. A validation rejection, such as a blank field or an oversize handoff, writes nothing; correct the named field before retrying. Any other failure, including a lost or unreadable tool result, may already have written earlier stages: writes run in order to report history, \`report.md\`, \`handoff.md\`, and \`status.json\`, so the report may be in history while \`report.md\`, \`handoff.md\`, or status is stale. Before any retry, inspect the actual files the result names, or the task folder when the result is unknown. \`failedStage\`, \`reportPath\`, and the flags are hints, not proof: \`failedWritePublished: true\` means the failed destination's text matches the attempted content, possibly because it already matched before this call. It does not prove this call wrote the file or that the write is durable; the failed stage's written flag remains \`false\`. Never resubmit a report that already has a history copy, and never claim a write you have not confirmed. \`report.md\` is stale only when the latest report write did not publish; an update that supplies only missing status, summary, or handoff fields does not refresh it, and nothing repairs it automatically until a later ordinary report write.`;

export const TASK_REPORT_OWNERSHIP_PROMPT = `## Task Report Ownership

A bound implementation Forager publishes its own report and successor handoff for its feature task and returns the numbered \`reportPath\`. When its result returns:
- Read the cited report. Check its content, evidence, and candidate against the Task Report Contract and the returned pin; a file at the path proves nothing by itself. Worker reports are attributed evidence and never prove integrated acceptance.
- Record status and a compact \`summary\` with \`hive_task_update\`. Do not retranscribe the worker's report or replace it with a shorter recap. When the worker had no metadata authority, persist the substantive narrative it returned as an attributed report yourself, and only for an actual feature task.
- When the worker's update failed or its result is unknown, you own the repair once the worker is terminal. Inspect report history, \`report.md\`, \`handoff.md\`, and status under the Task Report Contract, using the returned \`reportPath\` and flags as hints. Publish the returned narrative as an attributed report only after establishing that no history copy of it exists; \`success: false\` alone does not establish that. Write the returned handoff text only when inspection shows it did not publish, and never compose a handoff for the worker.
- Leave the successor handoff alone unless integration changes its facts.
- For material review findings on the task, append one consolidated decision report: for each finding, its location, cause or failure path, impact, evidence, and the decision (accepted, rejected, or deferred) with the reason and owner. A clean review needs no report. Reviewers stay read-only.
- After integration, or after target verification for a non-Git, report-only, or no-change result, append a closure report that a reader can follow on its own: the problem, the solution and how it works, issues met and their resolutions, references to the worker reports, the actual merge identity or verified target, integrated verification evidence, and remaining limits.

\`report.md\` mirrors the latest successful report write; it is not a separately maintained synthesis.`;

export const INTERRUPTED_WORKER_RECOVERY_PROMPT = `## Interrupted Worker Recovery

A native error, missing control return, provider failure, or host restart can end a worker run without a trustworthy terminal report. A failed run does not fail the task. When that happens:

1. Confirm the prior writer is truly terminal, along with any in-flight subprocess or shared-resource effect that could still change the worktree or external state, before any overlapping execution. The primary performs single direct reads itself: one \`hive_status\`, one worktree inspect, or one \`hive_task_trace_content\` spot-check of a known event ref. Route a named trace/lifecycle question with known native session/call identities to \`hive-helper\` when it needs multi-step forensics, including paging a trace; use supported native lifecycle and primary-owned board observations where they apply, and do not add polling. Spot-check decisive cited event refs with \`hive_task_trace_content\` before deciding. Helper gathers evidence; the primary decides termination. An unknown or open tool call, a cancellation acknowledgement, a stale board entry, or closed assistant text alone does not establish termination. Treat an idle runtime after a host restart and an \`evidence_only\` recovery snapshot as records of what survived, not as proof that the old writer or its subprocesses stopped. When a foreground \`task()\` call has no returned result, give Helper the parent's replay hint or ask it to find the \`child_session_id\` on that call in a \`hive_task_trace\` of the parent session; the background board lists only background launches. While termination stays uncertain, wait or ask instead of launching a replacement.
2. Inspect before any cleanup and preserve the failure evidence. Ask \`hive-helper\` one named question for an interrupted-worker evidence packet with the retained worktree, observed source HEAD, destination identity, dirty and untracked state, and, for a feature task, the report history, \`report.md\`, and \`handoff.md\` paths. Supply the feature/task or ad-hoc run identity, worktree path, known candidate and destination expectation. The primary performs any single direct status/inspection read or known-event spot-check itself; Helper handles the multi-step packet and performs no mutation or lifecycle decision.
3. Treat what survived as attributed evidence. A report written before the failed return is the prior worker's narrative, not proof of completion. A HEAD you discover is not a returned, verified pin; label it observed. When no terminal output exists, do not fabricate or transcribe one.
4. For a managed feature task, append an interruption observation as an attributed report: the known error and its source, last evidenced progress and verification, retained state, report references, unknowns, and the next action. Keep \`in_progress\` for a retry; set \`blocked\` only for a concrete unresolved operator or prerequisite decision, and \`failed\` only when the task cannot proceed. Ad-hoc work has no task records: keep the same observation in the session's lane inventory and terminal response. When a retained task lock, a filesystem fault, or unavailable inspection blocks the write, keep the observation in the session response, do not claim saved task state or delete the lock, and escalate the concrete blocker for supported or operator recovery before writing or retrying.
5. Launch a fresh recovery worker in the same retained worktree. Its assignment states the stopped-writer evidence, the report paths to read, the candidate and dirty state with what is attributable to the prior worker, the authorized scope, required checks, destination checkpoint duty, the pin to return, and where its account goes: a bound feature-task implementation assignment publishes a task report, while ad-hoc, diagnosis-only, or other recovery without metadata authority returns the narrative in its terminal response. Authorize adoption only of edits proven to come from the prior worker; dirty files are not worker-owned merely because they sit in the task worktree. Preserve unrelated or ambiguous edits, ignored dependencies and build output, and external resources, and never reset or clean the whole tree. The successor independently checks, adopts, or completes only the authorized edits, verifies them, and labels reconstructed accounts. With source-pin authority it returns a pin it verified in this session: a new commit, or the existing candidate commit when that needed no edits. Continuing the old session with \`task_id\` stays limited to what the Native Task Contract allows.`;
